FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Expose port
EXPOSE 3200

ENV PORT=3200

# Start in development mode
CMD ["npm", "run", "dev"]
